apiVersion: v1
kind: PersistentVolumeClaim
metadata:
{{- if .Values.persistence.annotations }}
  annotations:
{{- toYaml .Values.persistence.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
    {{- with .Values.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "sabnzbd.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
{{- toYaml .Values.persistence.accessModes | nindent 4 }}
{{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}