apiVersion: v1
kind: Service
metadata:
  name: {{ include "sabnzbd.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sabnzbd.selectorLabels" . | nindent 4 }}