apiVersion: v2
name: prowlarr
description: Prowlarr is a indexer manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Sonarr, Radarr, Lidarr, and Readarr offering complete management of your indexers with no per app Indexer setup required (we do it all).
appVersion: "2.0.5"
version: 1.0.0
kubeVersion: ">=1.19.0-0"
home: https://someadmin.com/helm-charts/prowlarr
icon: https://someadmin.com/images/someadmin-logo.png
sources:
  - https://github.com/someadmin-org/helm-charts
  - https://prowlarr.com/
  - https://github.com/Prowlarr/Prowlarr
  - https://docs.linuxserver.io/images/docker-prowlarr/
maintainers:
  - name: someadmin
    email: contact@someadmin.com
type: application
keywords:
  - prowlarr
  - nzb
  - usenet
  - indexer
  - download
  - someadmin
annotations:
  "artifacthub.io/operator": "false"
  "artifacthub.io/licenses": "MIT"
  "artifacthub.io/links.logo": https://someadmin.com/images/someadmin-logo.png
  "artifacthub.io/links.home": https://someadmin.com/helm-charts/prowlarr
  "artifacthub.io/links.maintainers": https://someadmin.com/helm-charts
  "artifacthub.io/links.source": "https://github.com/someadmin-org/helm-charts/tree/main/charts/prowlarr"
